name: Build and Deploy to DEV

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - nonprod
  push:
    branches:
      - nonprod

jobs:
  build-deploy:
    uses: ./.github/workflows/core.yml
    with:
      run-test: true
      run-deploy: if ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' && true || false }}
    secrets: inherit
