name: Build and Deploy to DEV

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, labeled]
    branches:
      - nonprod
  push:
    branches:
      - nonprod

jobs:
  test-and-deploy:
    name: Test and Deploy
    uses: ./.github/workflows/main.yml
    with:
      run-test: true
      run-deploy: true
      upload-report-github: false
      excel-test-path: /home/azureuser/data-dev.xlsx
    secrets: 
      REACT_APP_OPENFISCA_BASE_URL: ${{ secrets.REACT_APP_OPENFISCA_BASE_URL_DEV }}
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_DEV }}
      REACT_APP_REGISTRY_API_BASE_URL: ${{ secrets.REACT_APP_REGISTRY_API_BASE_URL_DEV }}
      AZURE_CREDENTIALS: ${{ secrets.SAFEGUARD_ESTIMATOR_INTEGRATIONS_AZURE_CREDS }}
      # VM CI only exists in PROD, so we use the PROD resource group for DEV as well
      AZURE_RESOURCE_GROUP_VM_CI: ${{ secrets.AZURE_RESOURCE_GROUP_PROD }}
      AZURE_VM_CI_NAME: ${{ secrets.AZURE_VM_CI_NAME_PROD }}
      COMMUNICATION_SERVICES_CONNECTION_STRING: ${{ secrets.COMMUNICATION_SERVICES_CONNECTION_STRING }}
      COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN: ${{ secrets.COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DEPLOY_SAS_URL: ${{ secrets.DEPLOY_SAS_URL_DEV }}
