name: Build and Deploy to PROD

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/main.yml
    with:
      run-test: false
      run-deploy: true
      upload-report-github: false
    secrets: 
      REACT_APP_OPENFISCA_BASE_URL: ${{ secrets.REACT_APP_OPENFISCA_BASE_URL_PROD }}
      REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL_PROD }}
      REACT_APP_REGISTRY_API_BASE_URL: ${{ secrets.REACT_APP_REGISTRY_API_BASE_URL_PROD }}
      AZURE_CREDENTIALS: ${{ secrets.SAFEGUARD_ESTIMATOR_INTEGRATIONS_AZURE_CREDS }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP_PROD }}
      AZURE_VM_NAME: ${{ secrets.AZURE_VM_NAME_PROD }}
      COMMUNICATION_SERVICES_CONNECTION_STRING: ${{ secrets.COMMUNICATION_SERVICES_CONNECTION_STRING }}
      COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN: ${{ secrets.COMMUNICATION_SERVICES_EMAIL_SENDER_DOMAIN }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      DEPLOY_SAS_URL: ${{ secrets.DEPLOY_SAS_URL_PROD }}
